---
properties:
- name: PREFIX
  value: "{{toolchain.name}}"
  type: text
- name: VPC_IMAGE_NAME
  value: "\\${PREFIX}-\\${DATE}"
  type: text
- name: COS_SERVICE_NAME
  value: "\\${PREFIX}-cos"
  type: text
- name: COS_SERVICE_PLAN
  value: "standard"
  type: text
- name: COS_REGION
  value: "\\$REGION"
  type: text
- name: COS_BUCKET_NAME
  value: "\\${PREFIX}-images"
  type: text
- name: DATACENTER
  value: "${DATACENTER}"
  type: text
- name: REGION
  value: "${REGION}"
  type: text
- name: RESOURCE_GROUP_NAME
  value: "${RESOURCE_GROUP_NAME}"
  type: text
- name: IBMCLOUD_API_KEY
  value: "${API_KEY}"
  type: secure
- name: SOFTLAYER_USERNAME
  value: "${SOFTLAYER_USERNAME}"
  type: text
- name: SOFTLAYER_API_KEY
  value: "${SOFTLAYER_API_KEY}"
  type: secure

stages:
- name: 'Initialize and Create Initial VSI'
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: git
    events: '{"push":true,"pull_request":false,"pull_request_closed":false}'
  jobs:
  - name: 'Initialize and Create Initial VSI'
    type: builder
    build_type: shell
    script: |+
      #!/bin/bash
      bash ./vpc-migrate-from-classic/pipeline_build.sh \
        000-prereqs.sh \
        010-prepare-cos.sh \
        020-create-classic-vm.sh

- name: 'Capture Initial VSI VHD to COS bucket'
  inputs:
  - type: job
    stage: 'Initialize and Create Initial VSI'
    job: 'Initialize and Create Initial VSI'
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 'Capture initial VSI VHD to COS bucket'
    type: builder
    build_type: shell
    script: |+
      #!/bin/bash
      bash ./vpc-migrate-from-classic/pipeline_build.sh \
        030-capture-classic-to-cos.sh

- name: 'Import VHD into VPC Image'
  inputs:
  - type: job
    stage: 'Capture Initial VSI VHD to COS bucket'
    job: 'Capture initial VSI VHD to COS bucket'
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 'Import VHD into VPC Image'
    type: builder
    build_type: shell
    script: |+
      #!/bin/bash
      bash ./vpc-migrate-from-classic/pipeline_build.sh \
        040-import-image-to-vpc.sh 

- name: 'Test VPC custom image'
  inputs:
  - type: job
    stage: 'Import VHD into VPC Image'
    job: 'Import VHD into VPC Image'
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 'Test VPC custom image'
    type: builder
    build_type: shell
    script: |+
      #!/bin/bash
      bash ./vpc-migrate-from-classic/pipeline_build.sh \
        050-provision-vpc-vsi.sh

- name: 'Clean up everything except COS instance and bucket'
  inputs:
  - type: job
    stage: 'Test VPC custom image'
    job: 'Test VPC custom image'
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 'Clean up'
    type: builder
    build_type: shell
    script: |+
      #!/bin/bash
      bash ./vpc-migrate-from-classic/pipeline_build.sh \
        060-cleanup.sh

- name: Manually Cleanup COS Instance and Bucket
  inputs:
  - type: job
    stage: 'Clean up COS instance and bucket'
    job: Clean up
  triggers:
  - type: stage
    enabled: false
  jobs:
  - name: 'Clean up'
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      bash ./vpc-migrate-from-classic/pipeline_build.sh \
        final_clean_up
